---
- name: Remove {{ app_name }} Web App
  hosts: localhost
  gather_facts: false

  collections:
    - redhat.openshift
    
  tasks:

  - block:

    - name: Login to OpenShift
      redhat.openshift.openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: no
      register: openshift_auth_results

    - name: Remove the {{ app_name }} service route
      redhat.openshift.openshift_route:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ openshift_fqdn }}"
        validate_certs: no
        service: "{{ app_name }}"
        state: absent
        namespace: default

    - name: Remove Service for the {{ app_name }} deployment
      redhat.openshift.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ openshift_fqdn }}"
        validate_certs: no
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}"
            namespace: default

    - name: Remove {{ app_name }} deployment
      redhat.openshift.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ openshift_fqdn }}"
        validate_certs: no
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ app_name }}"
            namespace: default
      
    always:
    - name: If login succeeded, try to log out (revoke access token)
      redhat.openshift.openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
      when: openshift_auth_results.openshift_auth.api_key is defined
