---
- name: Create Namespace on Openshift
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.openshift
    - kubernetes.core
    
  pre_tasks:
    - name: Login to OpenShift
      openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: no
      register: openshift_auth_results
    
  tasks:
     
    - name: Pull Pod list
      k8s_info:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: Pod
      register: pod_list
      
  always:
    - name: If login succeeded, try to log out (revoke access token)
      openshift_auth:
        state: absent
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      when: openshift_auth_results.openshift_auth.api_key is defined
