---
- name: Create Namespace on Openshift
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - redhat.openshift
    - kubernetes.core
    
  tasks:

  - block:


     
    - name: Pull Pod list
      k8s_info:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        kind: Pod
        validate_certs: no
      register: pod_list
      
    always:
    - name: If login succeeded, try to log out (revoke access token)
      openshift_auth:
        state: absent
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      when: openshift_auth_results.openshift_auth.api_key is defined
