---
- name: Deploy Tower Web App
  hosts: all
  gather_facts: false

  collections:
    - redhat.openshift
    - kubernetes.core
    
  tasks:

  - block:

    - name: Login to OpenShift
      openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: no
      register: openshift_auth_results

    - name: Create tower-demo deployment
      kubernetes.core.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: tower-demo
            namespace: default
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: tower-demo
            template:
              metadata:
                labels:
                  app: tower-demo
              spec:
                containers:
                - name: web
                  image: nginx:latest
                  livenessProbe:
                    tcpSocket:
                      port: 8080
                    timeoutSeconds: 1
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  ports:
                  - containerPort: 8080

    - name: Create Service for the tower-demo deployment
      kubernetes.core.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: tower-demo
            namespace: default
          spec:
            ports:
            - port: 443
              targetPort: 8080
            selector:
              app: tower-demo

    - name: Expose the tower-demo service externally
      redhat.openshift.openshift_route:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        termination: edge
        tls:
          insecure_policy: allow
        service: tower-demo
        namespace: default
      register: route

    - name: Search for all Pods labelled app=tower-demo
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - app = tower-demo
      register: pod
      
    - name: Copy HTML into Tower Pods
      command: "oc cp /home/openshift/html/ {{ item.metadata.name }}:/var/www/"
      loop: "{{ pod.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"

    - name: Display Link for Application
      debug:
        msg: "https://{{ route.result.spec.host }}"

    - name: Set stats for the e-mail body and ServiceNow
      set_stats:
        data:
          email_body: "tower-demo: https://{{ route.result.spec.host }} "
          work_notes: "[code]<a href='https://{{ route.result.spec.host }}'>tower-demo</a>[/code] "

    - name: Set stats for the e-mail subject
      set_stats:
        data:
          email_subject: "Ansible OpenShift Web Link"
      
    always:
    - name: If login succeeded, try to log out (revoke access token)
      openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
      when: openshift_auth_results.openshift_auth.api_key is defined
