---
- name: Pull Pod list
  hosts: all
  gather_facts: false

  collections:
    - redhat.openshift
    - kubernetes.core
    
  tasks:

  - block:

    - name: Login to OpenShift
      openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: no
      register: openshift_auth_results

    - name: Remove the insecure hello-world service route
      redhat.openshift.openshift_route:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        service: hello-kubernetes
        state: absent
        namespace: default
      register: route

    - name: Remove Service for the hello-world deployment
      kubernetes.core.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-kubernetes
            namespace: default

    - name: Remove hello-world deployment
      kubernetes.core.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-kubernetes
            namespace: default
      
    always:
    - name: If login succeeded, try to log out (revoke access token)
      openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: no
      when: openshift_auth_results.openshift_auth.api_key is defined
