---
- name: Test sat role
  hosts: localhost
  gather_facts: false

  tasks:
    - name: role
      ansible.builtin.uri:
        url: "{{ server_url }}/api/roles?per_page=100"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: true
        validate_certs: false
        body_format: json
      register: role
