---
- name: Test sat role
  hosts: localhost
  gather_facts: False

  tasks:
    - name: role
      ansible.builtin.uri:
        url: "{{ server_url }}/api/roles?per_page=100"
        method: GET
        validate_certs: False
        body_format: json
      register: role
