---
- name: Test sat role
  hosts: localhost

  tasks:
    - name: role
      redhat.satellite.role:
        name: "Provisioner"
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        description: "Only provision on libvirt"
        state: present
