---
- name: "Create the composite content view"
  redhat.satellite.content_view:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    organization: "{{ sat_organization }}"
    validate_certs: "{{ sat_validate_certs }}"
    name: "{{ cv.name }}"
    description: "{{ cv.desc }}"
    repositories: "{{ cv.repositories }}"
